apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: backend-feed
  labels: 
    app: backend-user
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: backend-feed
  template: 
    metadata: 
      labels: 
        app: backend-feed
    spec: 
      containers: 
      - name: udagram-api-feed
        image:  dattm283/udagram-api-feed:v3
        ports: 
        - containerPort: 8080