language: node_js
node_js:
  - 16

services:
  - docker

before_install:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-frontend ./udagram-api-frontend
  - docker build -t udagram-api-reverseproxy ./udagram-api-reverseproxy
  - docker tag udagram-api-feed dattm283/udagram-api-feed:v1
  - docker tag udagram-api-user dattm283/udagram-api-user:v1
  - docker tag udagram-api-frontend dattm283/udagram-api-frontend:v1
  - docker tag udagram-api-reverseproxy dattm283/udagram-api-reverseproxy:v1

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: main

script:
- bundle exec rake test