#!/bin/bash

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push dattm283/udagram-api-feed:v1
docker push dattm283/udagram-api-user:v1
docker push dattm283/udagram-api-frontend:v1
docker push dattm283/udagram-api-reverseproxy:v1